---
- name: ensure instances exists
  ec2: >
    id={{ item.name }}
    keypair={{ item.keypair|default(default_keypair) }}
    instance_type={{ item.instance_type|default(default_instance_type) }}
    image={{ item.image|default(default_image) }}
    wait=yes
    wait_timeout=500
    group={{ item.default_group|default(default_group) }}
    count=1
    instance_tags='{"Name":"{{ item.name }}"}'
  register: ec2
  with_items: instances
- debug: msg="Public address is {{ item.instances[0].public_dns_name }}"
  with_items: ec2.results
